version: '3.8'
services:
  backend:
    build: ../backend
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  frontend_node_modules:
